---
title: "P8105_HW_05"
author: "James Ng"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

* Problem Setup
```{r iris}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

* function code for filling in missing values
```{r function}
fill_in = function(x) {
  
  if (!is.numeric(x)) {
    replace_na(x,"virginica")
  } else if (is.numeric(x)) {
    replace_na(x,mean(x,na.rm=TRUE))
  }
  
}
```

* map function to fill in the missing values
```{r iris full}
iris_full=map(iris_with_missing,fill_in)
```

## Problem 2

```{r vector of csv}
vec_csv = str_c("./data/",list.files("./data"))
```

```{r function_2}
study_tidy = function(arm) {
  
  x = read_csv(arm)
  
  x %>% 
    janitor::clean_names() %>% 
    pivot_longer(
      week_1:week_8,
      names_to = "week",
      values_to = "observation"
      )
  
}
```

```{r one tibble}
study = 
  tibble(
    vec_csv = str_c("./data/",list.files("./data"))
  ) %>% 
  mutate(
    output = map(vec_csv, study_tidy),
    vec_csv = str_remove(vec_csv,"./data/"),
    vec_csv = str_remove(vec_csv,".csv")
  ) %>% 
  unnest(output) %>% 
  separate(vec_csv,c("arm","subject"),sep = "_",remove = TRUE)
```















